### ISSUE TITLE
manual added printers should not get deleted

### ISSUE THREAD

**Issue by rschetterer** [leoarnold/puppet-cups#10]
_Issue template: Please fill in the gaps_.

**Given** [ubuntu 16.04] 

Is there a way not do delete/touch manual added printers by users, which is common on laptops?
Recent only puppet defined printers are left after a puppet run ? 
Regards Robert

**Comment by leoarnold** [comment]
By default, the module only manages queues you declared in your manifest, and leaves all others untouched.

Unmanaged queues will only be deleted if you explicitly set

```puppet
class { '::cups':
  purge_unmanaged_queues => true # default: false
}
```

**Comment by rschetterer** [comment]
found it thx
Greetz Robert

**Comment by leoarnold** [comment]
**Note also:** When you are on a (wireless) network with printers shared via mDNS (MacBooks usually flood the network with printer announcements), your Avahi will install them.

I have not yet researched this problem in detail, but uninstalling Avahi will definitely stop it.

**Comment by rschetterer** [comment]
Hi, i think we allready did that, recent we have to think about how to manage
purge_unmanaged_queues parameter per role, cause we want have it set to false only for laptop role
Greetz Robert

**Comment by rschetterer** [comment]
final we find a solution to have purge_unmanaged_queues = false only on laptops
thx again
