### ISSUE TITLE
Availability of paperconfig is not ensured even if package_manage is true

### ISSUE THREAD

**Issue by wiene** [leoarnold/puppet-cups#107]
If the papersize is specified, this module does not ensure that the corresponding libpaper(-utils) package is installed (containing the used `paperconfig` tool) even if `package_manage` is set to `true`. As a result this module fails if the command `paperconfig` is not available.

**Comment by leoarnold** [comment]
Indeed. On which operating system did you notice?

**Comment by wiene** [comment]
I stumbled across this on CentOS 7 and [this](https://github.com/unibonn/puppet-cups/commit/98b7692e6f61af526e73bc14631fee84ee76c38d) is the way I fixed it.
