### ISSUE TITLE
Ability to control cups service and package installation

### ISSUE THREAD

**Issue by locnar1701** [leoarnold/puppet-cups#11]
As the page on puppet forge states, I should open an issue first, and not just put in a pull request:

The init.pp should pull from params.pp hiera data weather or not to install cups, or to enable it or not.  We have several dozen machines that ship with cups, and would like to use this module to manage the setup, but also have the ability to ensure cups is removed, or is installed, but not running.  Several distributions of linux ship with cups installed by default, and we need to manage them in a well understood method with contributed modules as we use the r10k/roles/profiles setup.

I can provide the pull request upon request.

**Comment by leoarnold** [comment]
This has already been discussed in #3 and my opinion still is

> The fundamental premise of this module is that you do want the CUPS daemon to be running and to manage queues. If that is not your intention, the module should not be including on that particular node.

**Comment by locnar1701** [comment]
Understood, but I still disagree.  If there were other printer systems that were available, and those were the default of dozens of distributions, sure. Cups is default on many distros, and enabled by default to run at the start.  We want to avoid special snowflake modules, or wrapper modules, and use yours to truly manage cups on each node.  Your module, your decision.  Thanks for replying.
