### ISSUE TITLE
AuthInfoRequired

### ISSUE THREAD

**Issue by felzmann** [leoarnold/puppet-cups#13]
Would it be possible to add support for the AuthInfoRequired key in printers.conf?

Possible choices should be "username,password", "negotiate" and "none".

**Comment by leoarnold** [comment]
Yes, this seems feasible. I'm adding it to the Roadmap for version 2.0.

**Development notes:**
- Manifest:
```puppet
cups_queue { 'Office':
  # ...
  options => { 'auth-info-required' => 'negotiate' }
}
```
- Getter: `query('auth-info-required')`
- Setter: `lpadmin('-E', '-p', name, '-o', "auth-info-required=#{value}")`
