### ISSUE TITLE
/var/log/cups/error_log flooded with SSL errors

### ISSUE THREAD

**Issue by olifre** [leoarnold/puppet-cups#140]
Checking the `error_log`, I find tons of these during each puppet run, making the log almost unparseable to a human:
```
E [16/Jun/2019:18:08:21 +0200] Fatal error during SSL shutdown!
E [16/Jun/2019:18:08:24 +0200] Fatal error during SSL shutdown!
```
I can reproduce that running `lpoptions -E -p queuename -l`. Dropping the `-E`, the error vanishes. 
It seems that is some kind of inconvenience / bug at least in CUPS on RHEL 7.6. 

However, that makes me wonder whether the easiest solution would be to just drop `-E` here:
https://github.com/leoarnold/puppet-cups/blob/e191aa55413393900d6737ca111618ad26b21761/lib/puppet/provider/cups_queue/cups.rb#L310-L319
since this communication is in any case happening on the very same machine, so there should be no gain by using SSL - an `-E` is also not used in `README.md`, for example.

**Comment by leoarnold** [comment]
Check syslog and audit log please. Sounds like AppArmor or SELinux intercepting.

**Comment by olifre** [comment]
> Check syslog and audit log please.

Both show nothing, and it also happens after disabling SELinux. This is vanilla CentOS 7.6 with the shipped CUPS version. 
It can be reproduced by running `lpoptions -E -p queuename -l` as root,
and does not happen when using `lpoptions -p queuename -l`.

**Comment by leoarnold** [comment]
Then `-E` will be removed in `2.2.2`.

**Comment by olifre** [comment]
Many thanks for the quick change and release!
