### ISSUE TITLE
Ubuntu 16.10 Ruby syntax error

### ISSUE THREAD

**Issue by threepistons** [leoarnold/puppet-cups#21]
**Given** Ubuntu 16.10 with Puppet Agent 3.8.7.  CUPS is not yet installed and would have been installed fresh onto this PC by this Puppet module, had it worked.

**When** I apply the manifest

```puppet
        class { 'cups':
          papersize    => 'A4',
          webinterface => true,
        }

        cups_queue { 'PostRoom826':
          ensure    => 'printer',
          uri       => 'ksmb://fontburn64.campus.ncl.ac.uk/CompSci826',
          ppd       => "${::ksmb::ppdpath}/KMbeuC554ux.ppd",
          accepting => true,
          enabled   => true,
        }
```

**In order to** add CUPS with a kerberised samba print queue.  The "ksmb://" URI is for the kerberisation backend and works using this version of puppet-cups on Debian Jessie.

**Then** I get the error message:

```Shell
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/cups_queue: /etc/puppet/modules/cups/lib/puppet/type/cups_queue.rb:185: syntax error, unexpected ':', expecting ')'
  newproperty(:members, array_matching: :all) do
                                       ^
/etc/puppet/modules/cups/lib/puppet/type/cups_queue.rb:252: syntax error, unexpected kEND, expecting $end on node 16dcompl018.ncl.ac.uk
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by leoarnold** [comment]
Are you sure about the version numbers? Ubuntu yakkety comes with Puppet 4.5, so 3.8 seems a bit odd. Also, Puppet 3 is EOL.

Moreover, please note that we had to suspend support for Ubuntu 16.10 due to #19.

**Comment by threepistons** [comment]
I'm closing this because the version of CentOS we are using on our Puppet master is not listed as compatible with this module.  Sorry for my lack of diligence in checking my platform before filing a bug.

**Comment by leoarnold** [comment]
I'd guess that the problem is not CentOS in general, but your master might be running on Ruby 1.8.x (EOL 2013), causing the syntax error.
