### ISSUE TITLE
missed packages

### ISSUE THREAD

**Issue by borwinius** [leoarnold/puppet-cups#22]
HI,

to use your module i need the ppd-package

for Debian : `openprinting-ppds`
for Suse: `OpenPrintingPPDs`

I have insert this manually in the file: `manifests/params.pp`

so that all host will install this packages.

**Comment by leoarnold** [comment]
AFAIK those packages are not required by CUPS and only contain "drivers". Whether you need this package or not strongly depends on the printer you are using.

By law of Demeter, I'd like keep the number of my dependencies minimal. Hence I am very reluctant to add such packages. Also, other people might then want to add `hplip`, ..., and we end up installing lots of vendor specific packages which might not be required by the given scenario.

My current recommendation to the use would be to use 

```puppet
# Debian case as an example
package { 'openprinting-ppds':
  ensure => present,
}

class { 'cups':
  require => Package['openprinting-ppds'],
}
```

Maybe I'll add something like

```puppet
class { 'cups':
  additional_packages => 'openprinting-ppds' # Not yet implement
}
```
in the future.
