### ISSUE TITLE
Module affects macos sierra clients

### ISSUE THREAD

**Issue by sazzle2611** [leoarnold/puppet-cups#24]
**Given** macos 10.12 sierra with Puppet Agent 4.9.0.

**When** The module is installed on the server but not used on the mac client, I know you don't support Darwin although I would love you to ;) 

**In order to** apply catalog on client

**Then** agent hangs for ages on all 4 of you cups facts and sometimes it even fails to complete. At best it takes over 20 minutes to run. After I uninstalled this module it runs in seconds but I use this module for linux clients.

Facter: fact "cups_classes" has resolved to [].
Facter: fact "cups_classmembers" has resolved to {}.
Facter: fact "cups_printers" has resolved to [].
Facter: fact "cups_queues" has resolved to [].

**Comment by leoarnold** [comment]
Since version 2.0 of this module will not include these facts anymore, the issue should not occur with upcoming versions.

That said, the module uses the exact same querying mechanism as the facts. It is likely, that even without the facts, using of the module would still be problematic.

**Comment by sazzle2611** [comment]
When is version 2.0 likely to be available?

**Comment by leoarnold** [comment]
No need to wait: Locate where `leoarnold-cups` was installed to using

```
sudo puppet module list
```

and delete the fact file using

```
sudo rm [modulepath here]/cups/lib/facter/cups.rb
```

then you can try version 1.2.2 without the facter delay.

*Note:* Puppet will notice that you tampered with the  files and refuse e.g. to upgrade the module. In those cases, you'll have to manually remove the module first using

```
sudo rm -rf [modulepath here]/cups
```

**Comment by sazzle2611** [comment]
That worked perfectly, thank you.
