### ISSUE TITLE
Cannot set ErrorPolicy using this module

### ISSUE THREAD

**Issue by Socob** [leoarnold/puppet-cups#25]
This is more of a feature request than a bug report.

**Given** any OS and Puppet/CUPS version.

**When** I try to set the `ErrorPolicy` line in `/etc/cups/printers.conf` using this module

**In order to** affect what happens when a job cannot be sent to a printer

**Then**: I do not see any way to do this with this module in its current form.

For example, from `man lpadmin`:
```
       -o printer-error-policy=name
            Sets the error policy to be  used  when  the  printer  backend  is
            unable  to  send  the job to the printer.  The name must be one of
            "abort-job", "retry-job", "retry-current-job", or  "stop-printer".
            The  default  error  policy  is  "stop-printer"  for  printers and
            "retry-current-job" for classes.
```
Other options for `lpadmin` (e. g. `-o printer-is-shared`, `-u allow`, `-u deny`) do have corresponding attributes in the `cups_queue` type.

**Comment by leoarnold** [comment]
It is implemented:

```puppet
cups_queue { 'Office':
  # ...
  options => { 'printer-error-policy' => 'abort-job' }
}
```

To see a full list of all options available for your queue, run `puppet resource cups_queue MyQueue`.

**Comment by Socob** [comment]
Oh – I thought it was only possible to specify options shown by `lpoptions -l`. Sorry about the noise.

**Comment by leoarnold** [comment]
That's indeed a flaw in the README.
