### ISSUE TITLE
Web interface not accesible

### ISSUE THREAD

**Issue by splummer** [leoarnold/puppet-cups#27]
**Given** Red Hat Enterprise Linux Server release 7.4 (Maipo) with Puppet 2017.2.1 and CUPS cups-1.6.3-29.el7.x86_64.

**When** I apply the manifest

```puppet
  class { '::cups':
    listen        => [ 'localhost:631', '/var/run/cups/cups.sock', "${::fqdn}:631" ],
    web_interface => true,
  }
```

**In order to**
Install the cups software and make the web interface accessible from off the machine.

**Then** I get the error message when attempting to access the web interface on ${::fqdn}:631

**Forbidden**

I then disabled puppet and added the line 
 **Allow from all** to the cupsd.conf
```Shell
<Location />
  Order allow,deny
  Allow from all
</Location>
<Location /admin>
  Order allow,deny
  Allow from all
</Location>
<Location /admin/conf>
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow from all
</Location>
<Location /admin/log>
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow from all
</Location>
```

I think the template needs to account for Allow from options. Omitting them seems to not allow access from off the box. Ideally you would be able to pass different IPs to the Allow from attributes.

**Comment by leoarnold** [comment]
Thank you for your bug report @splummer. I was able to reproduce this bug on CentOS 7.3. I did not foresee this use case. I think the best way to tackle this would be to add full access control for the API endpoints, and then set suitable defaults. This might take a little more time to come up with good modelling.

In the meantime I hope you can work with patching `templates/cupsd.conf.erb` on your Puppet Server or so.

**Comment by vmpr** [comment]
thanks for your great work @leoarnold - I`ve patched the template for now, so it works - looking forward to your next release, cheers

**Comment by leoarnold** [comment]
Sorry for following up so late @splummer. The next release of the module will make this possible by setting

```puppet
class { '::cups':
  listen        => [ '*:631', '/var/run/cups/cups.sock' ],
  location      => 'remote-admin',
  server_alias  => '*', # Optional, but necessary in some use cases
  web_interface => true
}
```
