### ISSUE TITLE
how to share printer on the network?

### ISSUE THREAD

**Issue by lesinigo** [leoarnold/puppet-cups#30]
Maybe I'm missing something here, but after setting `shared => true` on a `cups_queue` it is still impossible to print on that queue from the network, because [the `cupsd.conf` template](https://github.com/leoarnold/puppet-cups/blob/master/templates/cupsd.conf.erb#L13) has the root Location hardcoded with a default-deny and without any allow:
```apache
<Location />
  Order allow,deny
</Location>
```

As far as I know about CUPS, to actually be able to print from the network there must be an `Allow @LOCAL` (to allow printing from the subnets CUPS is listening on, this is what `cupsctl --share-printers` does) or an `Allow all` (to allow printing from remote subnets, this is what `cupsctl --share-printers --remote-any` does) in the root location. 

If this is correct I'd propose a new parameter on the `cups` class to choose between those three alternatives (no allows, allow local, allow all) and/or a list or hash to let the user specify more fine-grained access rules.

**Comment by lesinigo** [comment]
Just to clarify on the Allow all use case: we are trying to set up printing from a central CUPS system (with just [generic PostScript queues](https://github.com/leoarnold/puppet-cups/issues/28#issuecomment-346184681)) to remote offices connected via VPN and let each remote office manage the actual printer configuration and drivers on their local cups server.

The "office CUPS" needs to accept print jobs from the central one and they come through a routed VPN network with a source subnet different from the local office subnet that CUPS is listening on, so we need either an `Allow all` or to explicitly allow the remote subnet of the central CUPS server.

**Comment by leoarnold** [comment]
This is a known shortcoming since #27 and currently in development.

**Comment by mtsinc1** [comment]
I'll confess, I've found configuring CUPS frustrating, but this module did enough of the work for me that I think I can contribute to making it work for a shareable printing system.

Although CUPS security is fine-grained and a little mysterious, I think that there are 2 primary levels of interest:

1. Allowing users to submit jobs from other machines.
2. Allowing remote administration of the system via the IPP web interface.

To which at the next level one could add the ability to control print jobs, but for most of us, that's something we'd expect if we had submit rights.

To that end, I'd propose the following server-level parameters:

    print_from => [ allow-from list ],
    admin_from => [ allow-from list ],
    browseable  => yes/no,

The allow-from list is the usual stuff for Apache-style "Allow from" elements. _e.g.,_ '192.168.12.0/24', "mynetwork.com" and so forth. Extra points if you can change it to a "Deny from" by prefixing the source with a "!".

I think I can make these options work without a whole lot of effort if you're interested.

**Comment by mtsinc1** [comment]
Follow-up. Yes, I have made this work. Virtually as conceived, including the "!" prefix to create a Deny. The only alteration is that since "browseable" is Boolean, the valid options are true and false.

Purists might prefer a closer correspondence with the generated config file. It's no big deal to change from "browseable" to "browsing=on/off", if preferred.

**Comment by leoarnold** [comment]
Sorry for following up so late @lesinigo. The next release of the module will make this possible by setting

```puppet
class { '::cups':
  location      => 'share-printers'
}
```
