### ISSUE TITLE
RHEL6 support?

### ISSUE THREAD

**Issue by williamkorb** [leoarnold/puppet-cups#36]
_Requesting RHEL 6 support_.

**Given** RHEL 6.9 with Puppet Enterprise 2017.3 and CUPS cups-1.4.2-78.el6_9.x86_64.

**When** I have tried to configure via Hiera data as follows:

```puppet
cups::web_interface: false
cups::package_manage: false
cups::resources:
  mylp:
    ensure: printer
    uri: lpd://print.domain.lcl/mylp
```

**In order to** Do basic print queue configuration

**Then** I get the error message:

With package_manage set to true/default:

```Shell
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install cups-ipptool' returned 1: Error: Nothing to do
Error: /Stage[main]/Cups::Packages/Package[cups-ipptool]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install cups-ipptool' returned 1: Error: Nothing to do

```

With package_manage set to false:

```Shell
Error: /Stage[main]/Cups::Server::Services/Service[cups]: Failed to call refresh: Could not start Service[cups]: Execution of '/sbin/service cups start' returned 1: Starting cups: cupsd: Child exited with status 1!
[FAILED]
Error: /Stage[main]/Cups::Server::Services/Service[cups]: Could not start Service[cups]: Execution of '/sbin/service cups start' returned 1: Starting cups: cupsd: Child exited with status 1!
[FAILED]
Info: Class[Cups]: Unscheduling all events on Class[Cups]
Info: Stage[main]: Unscheduling all events on Stage[main]
Error: Could not find a suitable provider for cups_queue
```

**Comment by leoarnold** [comment]
We never supported RHEL 6, but you might be able to get it to work: You will need to install the `ipptool` binary yourself as it does not ship with CUPS 1.4. Any version of `ipptool` should do, so copy it over from a contemporary CentOS / Fedora or compile it from source. Write a manifest which installs (say) `/usr/bin/ipptool/` before handling `class { 'cups': package_names => 'cups' }`. Hope that does the trick for you.

**Comment by leoarnold** [comment]
Closed due to inactivity.
