### ISSUE TITLE
returned 1: lpadmin: Success

### ISSUE THREAD

**Issue by threepistons** [leoarnold/puppet-cups#61]
**Given** Ubuntu 18.04.1 with Puppet 5.5.6 and CUPS 2.2.7.

**When** I apply the manifest

```puppet
lookup('classes', {merge => unique}).include
```
in site.pp and then the following hiera:
```yaml
classes:
  - types
  - ksmb
  - cups

types::files:
  '/usr/share/cups/model/KOC658UX.ppd':
    ensure: file
    replace: yes
    source: puppet:///modules/fileserver/ppds/KOC658UX.ppd
    mode: '0644'
    group: lp

cups::resources:
  USB_Building_Printing:
    ensure: printer
    uri: ksmb://cs-print/USB-BUILDING-PRINTING
    ppd: '/usr/share/cups/model/KOC658UX.ppd'
    make_and_model: 'KONICA MINOLTA C658SeriesPS(P)'
    shared: false
    enabled: true
    accepting: true
    description: All Urban Sciences printers, swipe your campus card at any printer to collect your job.
    options:
      KMDuplex: 2Sided
      PageSize: A4
      PaperSources: PC215
      Finisher: FS533
      KOPunch: PK519-4
      SaddleUnit: None
      PrinterHDD: HDD
      SelectColor: Grayscale
      Model: C458
      TextPureBlack: On

cups::default_queue: USB_Building_Printing
cups::papersize: A4
```

**In order to** create a [ksmb queue](https://github.com/threepistons/cups-ksmb) using the Konica Minolta driver sourced in the manifest.

**Then** I get the error message:
(run puppet agent -td)
```Shell
Debug: IPP query 'ipptool -c ipp://localhost/printers/USB_Building_Printing /dev/stdin' failed.
EXITCODE: 1
STDIN:
            {
              OPERATION Get-Printer-Attributes
              GROUP operation
              ATTR charset attributes-charset utf-8
              ATTR language attributes-natural-language en
              ATTR uri printer-uri $uri
              STATUS successful-ok
              DISPLAY device-uri
            }

STDOUT:

STDERR:
successful-ok

Debug: Executing: '/usr/sbin/lpadmin -E -p USB_Building_Printing -o KMDuplex=2Sided'
Debug: Executing: '/usr/sbin/lpadmin -E -p USB_Building_Printing -o PageSize=A4'
Debug: Executing: '/usr/sbin/lpadmin -E -p USB_Building_Printing -o PaperSources=PC215'
Debug: Executing: '/usr/sbin/lpadmin -E -p USB_Building_Printing -o Finisher=FS533'
Debug: Executing: '/usr/sbin/lpadmin -E -p USB_Building_Printing -o KOPunch=PK519-4'
Error: Execution of '/usr/sbin/lpadmin -E -p USB_Building_Printing -o KOPunch=PK519-4' returned 1: lpadmin: Success
Error: /Stage[main]/Cups::Queues::Resources/Cups_queue[USB_Building_Printing]/options: change from {"Finisher"=>"FS533", "KMDuplex"=>"2Sided", "KOPunch"=>"None", "Model"=>"C658", "PageSize"=>"A4", "PaperSources"=>"PC215", "PrinterHDD"=>"HDD", "SaddleUnit"=>"None", "SelectColor"=>"Auto", "TextPureBlack"=>"Auto"} to {"Finisher"=>"FS533", "KMDuplex"=>"2Sided", "KOPunch"=>"PK519-4", "Model"=>"C458", "PageSize"=>"A4", "PaperSources"=>"PC215", "PrinterHDD"=>"HDD", "SaddleUnit"=>"None", "SelectColor"=>"Grayscale", "TextPureBlack"=>true} failed: Execution of '/usr/sbin/lpadmin -E -p USB_Building_Printing -o KOPunch=PK519-4' returned 1: lpadmin: Success
Notice: /Stage[main]/Cups::Queues::Default/Exec[cups::queues::default]: Dependency Cups_queue[USB_Building_Printing] has failures: true
Warning: /Stage[main]/Cups::Queues::Default/Exec[cups::queues::default]: Skipping because of failed dependencies
Debug: /Stage[main]/Cups::Queues::Default/Exec[cups::queues::default]: Resource is being skipped, unscheduling all events
Debug: Class[Cups::Queues::Default]: Resource is being skipped, unscheduling all events
Debug: Class[Cups::Queues::Resources]: Resource is being skipped, unscheduling all events
Debug: Class[Cups::Queues]: Resource is being skipped, unscheduling all events
Debug: Class[Cups]: Resource is being skipped, unscheduling all events
Info: Class[Cups]: Unscheduling all events on Class[Cups]
```
Even thought the queue has been added (```lpstat -p``` confirms it), I get red error text in the Puppet run, and the setting of the default queue and restarting of the daemon is skipped.

Each time I attempt the Puppet run, the key-value pair in ```/usr/sbin/lpadmin -E -p USB_Building_Printing -o key=value``` is different, but each time the last one says "returned 1: lpadmin: Success".  If I run those lpadmin commands at the command line as root, they exit with 0.

**Comment by leoarnold** [comment]
Some observations here:
- `ipptool -c [...]` exits 1, but claims `successful-ok`, but on STDERR. We have seen such strange behavior in #19 where it was caused by a patch to CUPS by the Debian team.
- Because of #19 a fallback mechanism using `ipptool -t [...]` was added to the module (2.0.0 and above). This fallback, however, was skipped in your execution.
- The `returned 1: lpadmin: Success` points to a new and unexpected behavior of CUPS - or maybe the dash in `PK519-4` was not escaped properly when shelling out.

I'll try to confirm it in a Vagrant box.

**Comment by threepistons** [comment]
I missed the detail that types::files is supplied by ghoneycutt-types from the forge.  It allows me to make files, packages, etc without having many stanzas in site.pp of the form:
```Puppet
$packages = lookup('packages')
$packages.each | $key, $value | {
  package {$key:
    * => $value
  }
}
```

**Comment by leoarnold** [comment]
I have narrowed the problem down to the fact that all commands are issued correctly, but on the system you describe, all commands using encrypted communication (i.e. the `-E` in `lpadmin -E`) will exit 1 despite achieving success.

I have checked this behavior with PPD files from several vendors and - as to be expected, see https://github.com/leoarnold/puppet-cups/issues/6#issuecomment-225221877 - this problem only seems to arise with PPD files from KonicaMinolta.

Your CUPS installation now seems to mind these aberrations more than before - at least when using encrypted communication. I have also run your configuration against Fedora 28 with CUPS 2.2.6 where the problems do not arise, so it was either introduced by CUPS 2.2.7 or a patch by the Debian / Ubuntu community.

While dropping the usage of the `'-E'` flag in `lib/puppet/provider/cups_queue/cups.rb` would solve your issue _for now_, it is merely a cure of the symptom, not of the underlying issue, so we're reluctant to do that. Also, lowering your security standards to overcome someone else's bug never seems to be a good idea. Nevertheless it would be a hot fix you could apply locally to your setup to get it running until there's a better option.

Let's keep this issue open to see how many users are actually affected. If the issue becomes big enough, we'll have to add more error handling to the module.

**Comment by threepistons** [comment]
I will try editing my PPD file.  Thank you for the heads-up.

**Comment by threepistons** [comment]
I've updated to a more recent PPD and also stripped lines out of it based on #19.  I still get
```Shell
root@17dcompd454:/usr/share/cups/model# ipptool -t ipp://localhost/printers/USB_Building_Printing /usr/share/cups/ipptool/get-printer-attributes.test
"/usr/share/cups/ipptool/get-printer-attributes.test":
    Get printer attributes using Get-Printer-Attributes                  [FAIL]
        RECEIVED: 10361 bytes in response
        status-code = successful-ok (successful-ok)
        Duplicate "pwg-raster-document-type-supported" attribute in printer-attributes-tag group
        Duplicate "pwg-raster-document-resolution-supported" attribute in printer-attributes-tag group
```
(an Ubuntu/Debian bug?) and
```Shell
Debug: IPP query 'ipptool -c ipp://localhost/printers/USB_Building_Printing /dev/stdin' failed.
EXITCODE: 1
STDIN:
            {
              OPERATION Get-Printer-Attributes
              GROUP operation
              ATTR charset attributes-charset utf-8
              ATTR language attributes-natural-language en
              ATTR uri printer-uri $uri
              STATUS successful-ok
              DISPLAY printer-make-and-model
            }

STDOUT:

STDERR:
successful-ok
```
when I run ```puppet agent -td``, but the queues are forming consistently.

I attach my [new and amended PPD](https://github.com/leoarnold/puppet-cups/files/2442936/KOC759UX.ppd.txt) for testing and also in the hope that it will be useful for anyone else using Konica Minolta C759, C659, C658, C558, C458, C368, C308, C258, C287, C227, C3851, C3851FS, or C3351 and tearing their hair out.

**Comment by leoarnold** [comment]
The duplicates in the IPP response stem from this Debian patch:
https://sources.debian.org/patches/cups/2.1.3-5/pwg-raster-attributes.patch/

The debug message comes from calling `Puppet.debug` in the `rescue` branch of
https://github.com/leoarnold/puppet-cups/blob/ab42f4c9fbc688d46cdddcb60c3b841f2855c50e/lib/puppet_x/cups/ipp.rb#L31-L36
Maybe this should be replaced with a less noisy message.

**Comment by threepistons** [comment]
> Maybe this should be replaced with a less noisy message.

It's apparent from the earlier issue with Konica PPDs that this will affect anyone with certain Konica models, and it seems unlikely that Konica are going to publish PPDs that pass `cupstestppd` in the foreseeable future.

Suggestion: If your module is able to detect that a PPD is from Konica (I'm guessing "yes" because the PPD says _*Manufacturer: "KONICA MINOLTA"_ on line 8), maybe the error can say something about Konica PPDs being not compliant with RFC 2911 and directing them to #6 or a similar piece of documentation?  It seems likely that queries like this will arise again because of Konica's dominance in the "pull printing" (ie authenticated job release) market, if the error message tells people what to do, you get fewer issues.
