### ISSUE TITLE
Cannot set options in cupsd.conf

### ISSUE THREAD

**Issue by IHOPKCdavidgagne** [leoarnold/puppet-cups#7]
**Given** Centos7 with Ruby 2.0.0, Puppet 3.8.7 and CUPS 1.6.3.

**In order to**
Set options in cupsd.conf such as listening interface.

**Then** Option not available.

It would be nice to be able to set options in cupsd.conf such as listening interface. Not sure if it also adds firewall opening. Would be nice to be able to fully stand up working cups just from manifest.

**Comment by leoarnold** [comment]
Release 1.3.0 will have a feature to do this, see [here](https://github.com/leoarnold/puppet-cups#define-cupsdirective).

**Comment by leoarnold** [comment]
@IHOPKCdavidgagne I am thinking of implementing a new defined type like

```
cups::server { 'cups':
  browsing => false,
  ...
}
```

Which directives from the `.conf` files would be most important for you?

**Comment by IHOPKCdavidgagne** [comment]
The only thing I'm using that's not default is the listening interface.

**Comment by leoarnold** [comment]
@IHOPKCdavidgagne I guess you have come up with your own solution for this, but I'm going to list several alternatives for the general audience here:

**file** Write a `cupsd.conf` with your desired configuration and enforce it like this
```Puppet
class { '::cups': }

file { '/etc/cups/cupsd.conf':
  ensure  => 'file',
  owner   => 'root',
  group   => 'group',
  mode    => '0640',
  source  => 'puppet:///modules/mymodule/cupsd.conf',
  require => Package['cups'],
  notify  => Service['cups'],
}
```

**augeas**
```Puppet
class { '::cups': }

augeas { 'cupsd.conf':
  context => '/files/etc/cups/cupsd.conf',
  changes => [
    'rm directive[ . = "Listen" ]',
    'ins directive before directive[1]',
    'set directive[1] Listen',
    'set directive[1]/arg "localhost:631"',
    'ins directive before directive[1]',
    'set directive[1] Listen',
    'set directive[1]/arg "/var/run/cups/cups.sock"',
  ]
  require => Package['cups'],
  notify  => Service['cups'],
}
```

**ERB template** The next release of this module will implement a [template](https://github.com/leoarnold/puppet-cups/blob/5d7767149066f66f2f148f026d17aa8a3cc23879/templates/cupsd.conf.erb) to provide the full set of options available for the CUPS server.

**Comment by lordbink** [comment]
Any news on the next release? I was looking to start using the features of server.pp when I noticed that was only in master. I went to test master to find out that I get an error from the agent when applying.

For reference this is the error, however, it may be unrelated to this issue. If that is the case I can create another issue.

`Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at 'Array'; expected ')' at /etc/puppet/environments/signal_print_updates/modules/cups/manifests/init.pp:4 on node signal-print.mbx.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

**Comment by leoarnold** [comment]
@lordbink I am currently thinking about how to design the 2.0 API. There are quite some features worth to be added and I do not want to break the API too often. I'm aiming for June 2016 with the next stable release, and more agile development thereafter.
