### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by roumano** [leoarnold/puppet-cups#81]
Hi,

If possible, please create a new version as it's still use the v2.0.3 in puppet ( https://forge.puppet.com/leoarnold/cups ) and you can greatly improve it since : 

> released this on 18 Jan · 73 commits to master since this release

**Comment by leoarnold** [comment]
This "issue" (actually comment) suggest to create an new release for the mere reason of having an incremented version number and freshend release date.

The module will not have a new release until relevant changes have been implemented.
