### ISSUE TITLE
It would be nice to be able to install drivers using the open printing module

### ISSUE THREAD

**Issue by IHOPKCdavidgagne** [leoarnold/puppet-cups#9]
**Given** Centos7 with Ruby 2.0.0, Puppet 3.8.7 and CUPS 1.6.3.

**When** I apply the manifest

**In order to** Install Printer Drivers Using Open Printing

**Then** Not implemented

It would be great if there was a way to specify which print drivers you wanted to install via open printing (http://www.openprinting.org/printers) or maybe even from manufacturers downloads. 

Way more bonus points if it can implement Windows Printer Driver auto install as well (https://wiki.samba.org/index.php/Configuring_Point'n'Print_automatic_printer_driver_deployment)

**Comment by leoarnold** [comment]
As far as I can see, openprinting.org does not offer a unified approach for retrieving printer drivers. Manufacturer websites (especially Brother) will go far to force you to accept their EULA, so if there is a way to script this, they would likely block it soon after.

Bottom line: Retrieving the driver is left as an exercise to the user. Luckily you only have to do it once and can then systematically distribute it from the master.

The "Windows Printer Driver auto install" is a SAMBA feature and not in any way related to CUPS. Hence such functionality would be misplaced in this module.

**Comment by IHOPKCdavidgagne** [comment]
You might be able to get away with HPLIP at least. 

It appears open printing was working on getting it to work with package managers, and maybe it works with ubuntu now? I'll go bug them about getting it on yum based systems...

https://wiki.linuxfoundation.org/en/OpenPrinting/Database/DriverPackages

**Comment by IHOPKCdavidgagne** [comment]
Maybe this...
http://www.openprinting.org/download/printdriver/mkreporpm

**Comment by leoarnold** [comment]
No, that script just generated the repo

http://www.openprinting.org/download/printdriver/RPMS/x86_64/

which contains RPMs from 2010.

Ubuntu ships with packages like `hplip` and `openprinting-ppds`. Centos and friends may have something similar. This module will not install them by default, as many people might not need them.

Still, it seems there is no suitable way of autoretrieving the driver.

Security-wise it would also be very bothersome to have Puppet retrieve files from the internet.

**Comment by leoarnold** [comment]
Closing issue due to infeasibility of desired outcome.
